version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chattingo-network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - chattingo-network

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    networks:
      - chattingo-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - chattingo-network

volumes:
  mysql_data:

networks:
  chattingo-network:
    driver: bridge
