apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-frontend-deployment
  labels:
    app: chattingo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chattingo-frontend
  template:
    metadata:
      labels:
        app: chattingo-frontend
    spec:
      containers:
        - name: chattingo-frontend
          image:     routparesh/chattingo-frontend:a3505cf0d5d15ee4fcf48c6d31209178d2b2939f
          ports:
            - containerPort: 80
