apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-frontend-deployment
  labels:
    app: chattingo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chattingo-frontend
  template:
    metadata:
      labels:
        app: chattingo-frontend
    spec:
      containers:
        - name: chattingo-frontend
          image:    routparesh/chattingo-frontend:e92861bbd8fa2734e97899fe616c0250d7c49ded
          ports:
            - containerPort: 80
